import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FormField } from '../componenet'
import { TailSpin } from 'react-loader-spinner'
import { getRandomPrompt } from '../utils'

function CreatePost() {

  const navigate = useNavigate()
  const [form,setForm] = useState({name:'',prompt:'',photo:''})
  const [generatingImage,setGeneratingImage] = useState(false)
  const [loading,setLoading] = useState(false)

  const handleSubmit = async (e)=>{
    e.preventDefault()
    if(form.name && form.photo){
      setLoading(true)
      try {
        const response = await fetch("http://127.0.0.1:8000/api/post_image/",{
          method:"POST",
          headers:{
            "Content-Type":"application/json",
          },
          body:JSON.stringify({"name":form.name,"photo":form.photo,"prompt":form.prompt})
        })
        await response.json()
        navigate('/')
      } catch (error) {
        alert(error)
      }finally{
        setLoading(false)
      }
    }
  }

  const handleChange = (e)=>{
    setForm({...form, [e.target.name]:e.target.value})
  }

  const handleSurpriseMe = ()=>{
    const randomPrompt = getRandomPrompt(form.prompt)
    setForm({...form, prompt:randomPrompt})
  }

  const generateImage = async ()=>{
    if(form.prompt){
      try{
        setGeneratingImage(true)
        const response = await fetch('http://127.0.0.1:8000/api/generate_image/',{
          method:"POST",
          headers:{
            "Content-Type":"application/json",
          },
          body:JSON.stringify({name:form.name,prompt:form.prompt})
        })
        const data = await response.json()
        setForm({...form,photo: await data.photo})

      }catch(error){
        alert(error)
      }finally{
        setGeneratingImage(false)
      }
    }else{
      alert("Please Enter a prompt")
    }
  }

  return (
       <section className='max-w-7xl mx-auto'>

      <div >
        <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>
          Create imaginative and visually stunning image generated by me
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField 
            labelName='Your Name'
            type='text'
            name='name'
            placeholder='Leo Messi'
            value={form.name}
            handleChange={handleChange} />

          <FormField 
            labelName='Prompt'
            type='text'
            name='prompt'
            placeholder='A Dinosaur exploring Chittagong, photography'
            value={form.prompt}
            handleChange={handleChange} 
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
            />
      <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg
      focus:ring-blue-500 focus:border-blue-500 w-64 p-3 mt-2 h-64 flex justify-center items-center'>
        {form.photo ? 
        <img src={form.photo} alt={form.prompt} className='w-full h-full object-contain'/> : 
        <img src='https://t3.ftcdn.net/jpg/02/48/42/64/360_F_248426448_NVKLywWqArG2ADUxDq6QprtIzsF82dMF.jpg' className='w-9/12 h-9/12 opacity-40 object-contain'/>}
        {generatingImage && <div className='absolute inset-0 z-0 flex 
        justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
          <TailSpin 
            height="80"
            width="80"
            color="white"
            ariaLabel="tail-spin-loading"
            radius="1"
            visible={true}/>
          </div>}
          </div>
        </div>

          <div className='mt-5 flex gap-5'>
            <button className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5
            text-center'
            type='button'
            onClick={generateImage}
            >
              {generatingImage ? "Generating..." : "Generate"}
            </button>
          </div>

          <div className='mt-10'>
            <p className='mt-2 text-[#666e75] text-14px'>
              You can share the images with your friends and your community.
            </p>
            <button type='submit' className='mt-3 text-white bg-[#6469ff] font-medium rounded-md
            text-sm w-full sm:w-auto px-5 py-2.5 text-center'>
              {loading ? 'Sharing...' : "Share with your friends"}
            </button>
          </div>

      </form>
    
    </section>
  )
}

export default CreatePost