# Generated by Django 4.1 on 2023-04-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
    ]
