# Generated by Django 4.1 on 2023-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="prompt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
